{{- if .Values.jupyter.enabled }}
{{- if .Values.jupyter.persistence.notebooks.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "datalakehouse.fullname" . }}-jupyter-notebooks-pvc
  labels:
    {{- include "datalakehouse.jupyter.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.jupyter.persistence.notebooks.size }}
  {{- if or .Values.jupyter.persistence.notebooks.storageClass .Values.global.storageClass }}
  storageClassName: {{ .Values.jupyter.persistence.notebooks.storageClass | default .Values.global.storageClass }}
  {{- end }}
---
{{- end }}
{{- if .Values.jupyter.persistence.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "datalakehouse.fullname" . }}-jupyter-data-pvc
  labels:
    {{- include "datalakehouse.jupyter.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.jupyter.persistence.data.size }}
  {{- if or .Values.jupyter.persistence.data.storageClass .Values.global.storageClass }}
  storageClassName: {{ .Values.jupyter.persistence.data.storageClass | default .Values.global.storageClass }}
  {{- end }}
{{- end }}
{{- end }}